[package]
name = "backdoor-ai"
version = "0.1.0"
description = "BackDoor AI Tauri Rust Desktop Assistant"
authors = ["Antigravity"]
edition = "2021"

[[bin]]
name = "BackDoor-AI"
path = "src/main.rs"

[build-dependencies]
tauri-build = { version = "^2.6.3", features = [] }

[dependencies]
tauri = { version = "^2.11.2", features = ["tray-icon"] }
serde = { version = "^1.0.210", features = ["derive"] }
serde_json = "^1.0.128"
rusqlite = { version = "^0.31.0", features = ["bundled"] }
tokio = { version = "^1.40.0", features = ["full"] }
reqwest = { version = "^0.12.7", features = ["json", "multipart", "stream", "blocking"] }
rand = "^0.8.5"
keyring = "^2.1.6"
windows-sys = { version = "^0.52.0", features = ["Win32_System_JobObjects", "Win32_Foundation", "Win32_System_Threading", "Win32_Security", "Win32_Graphics_Gdi", "Win32_UI_WindowsAndMessaging", "Win32_System_Com"] }
windows = { version = "^0.58.0", features = ["Media_Ocr", "Graphics_Imaging", "Storage_Streams", "Foundation", "Globalization", "Media_SpeechRecognition"] }
cpal = "^0.15.3"
hound = "^3.5.0"
tauri-plugin-global-shortcut = "^2.3.2"
eventsource-stream = "^0.2.3"
futures = "^0.3.34"
uuid = { version = "^1.24.1", features = ["v4"] }

[features]
default = ["custom-protocol"]
custom-protocol = ["tauri/custom-protocol"]
